export default {
  MODAL_NEW_ACTIVE: '@modal/MODAL_NEW_ACTIVE',
  MODAL_CEI_IMPORT: '@modal/MODAL_CEI_IMPORT',
  MODAL_BOND: '@modal/MODAL_BOND',
  MODAL_STOCK_QUERY: '@modal/MODAL_STOCK_QUERY',
  MODAL_STOCK_QUERY_CHART: '@modal/MODAL_STOCK_QUERY_CHART',
  MODAL_STOCK_QUERY_DIVIDENDS: '@modal/MODAL_STOCK_QUERY_DIVIDENDS',
  CLOSE_ALL: '@modal/CLOSE_ALL',
};
