export default {
  OPEN_MODAL_NEWSTOCK: '@modal/OPEN_MODAL_NEWSTOCK',
  OPEN_MODAL_CEIIMPORT: '@modal/OPEN_MODAL_CEIIMPORT',
  OPEN_MODAL_BOND: '@modal/OPEN_MODAL_BOND',
  CLOSE_ALL: '@modal/CLOSE_ALL',
};
